name: WaypointBeacons
version: 0.3_FunctionalButMissingFeatures
main: me.obverser.waypointbeacons.WaypointBeacons
api-version: 1.13
authors: [Gabe10611]
description: A beacon based, rpg-like waypoint system.
